--SQL SERVER PRACTICAL EXAM

--QUESTION1

CREATE DATABASE SERVEREXAM;

CREATE TABLE EMPLOYEE
(
EMP_ID INT,
EMP_NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY INT,
JOINDATE DATE
);

INSERT INTO EMPLOYEE
VALUES
(101,'   VARUN','HR',74000,'2024-11-25'),
(102,'ROY   ','TEACHING',50000,'2020-04-14'),
(103,'  SASHA  ','FINANCE',95000,'2021-07-04'),
(104,'     ARJUN  ','IT',70000,'2023-11-25'),
(105,'HEMA ','TEACHING',52000,'2021-05-14'),
(106,'      INDU     ','CODING',195000,'2019-04-04'),
(107,' ROY ','ANALYST',154000,'2025-08-15'),
(108,'      SEB    ','IT',80000,'2022-07-17');

SELECT * FROM EMPLOYEE;

--QUESTION2

SELECT TRIM(EMP_NAME) AS EMP_NAME
FROM EMPLOYEE;

UPDATE EMPLOYEE
SET EMP_NAME = TRIM(EMP_NAME);

SELECT REPLACE(DEPARTMENT,'FINANCE','ACCOUNTS') 
AS DEPARTMENTS
FROM EMPLOYEE;

--QUESTION3

SELECT EMP_ID,
       EMP_NAME,
       SALARY,
       AVG(SALARY) OVER() AS AVGSAL
FROM EMPLOYEE;

SELECT EMP_ID,
       EMP_NAME,
       SALARY,
       ROW_NUMBER() OVER(ORDER BY EMP_ID) 
       AS ROWNUM
FROM EMPLOYEE;

SELECT EMP_ID,
       EMP_NAME,
       SALARY,
       RANK() OVER(ORDER BY SALARY DESC) 
       AS SALRANK
FROM EMPLOYEE;

--QUESTION4

SELECT EMP_ID,
       EMP_NAME,
       SALARY,
       LAG(SALARY) OVER (ORDER BY EMP_ID) 
       AS PREVSAL
FROM EMPLOYEE;

SELECT EMP_ID,
       EMP_NAME,
       SALARY,
       LEAD(SALARY) OVER (ORDER BY EMP_ID) 
       AS NEXTSAL
FROM EMPLOYEE;

--QUESTION5

SELECT EMP_ID,
       EMP_NAME,
       DEPARTMENT,
       SALARY,
       AVG(SALARY) OVER (PARTITION BY DEPARTMENT) 
       AS DEP_AVG_SAL
FROM EMPLOYEE;

----------------------------------------------------------------------------

--QUESTION6

CREATE TABLE STUDENTS 
(
STUDENT_ID INT,
STUDENT_NAME VARCHAR(50),
MARKS INT
);

INSERT INTO STUDENTS
VALUES
(101, 'BOB', 62),
(102, 'JUAN', 77),
(103, 'KARTHIK', 91),
(104, 'DAVE', 47),
(105, 'EVA', 85),
(106, 'GINA', 65);

SELECT STUDENT_ID,
       STUDENT_NAME,
       MARKS,
       CASE
           WHEN MARKS >= 90 THEN 'A GRADE'
           WHEN MARKS >= 75 THEN 'B GRADE'
           WHEN MARKS >= 60 THEN 'C GRADE'
           ELSE 'FAIL'
       END AS GRADE
FROM STUDENTS;

----------------------------------------------------------------------------

--QUESTION7

CREATE TABLE EMPLOYEECONTACT 
(
EMP_ID INT,
EMP_NAME VARCHAR(50),
PHONE VARCHAR(20)
);

INSERT INTO EMPLOYEECONTACT 
VALUES
(1, 'ARNAV','5589873210'),
(2, 'RITU',NULL),
(3, 'KEVIN','9123474574'),
(4, 'SEB',NULL),
(5, 'EMMA','9854776655');

SELECT * FROM EMPLOYEECONTACT;

SELECT EMP_ID,
       EMP_NAME,
       COALESCE(PHONE,'PHONE NOT AVAILABLE') 
       AS PHONE
FROM EMPLOYEECONTACT;

----------------------------------------------------------------------------

--QUESTION8

SELECT DATEADD(DAY,15,GETDATE()) AS DATE_15DAYS;

SELECT DATEADD(MONTH,6,GETDATE()) AS DATE_6MONTHS;

SELECT DATEADD(YEAR,2,GETDATE()) AS DATE_2YEARS;

SELECT DATEADD(DAY,-30,GETDATE()) AS DATE_30DAYS;

----------------------------------------------------------------------------

--QUESTION9

SELECT DATEDIFF(DAY,'2022-08-04',GETDATE()) 
AS DAYDIFF;

SELECT DATEDIFF(MONTH,'2021-08-21','2026-04-17') 
AS MONTHDIFF;

SELECT EMP_ID,
       EMP_NAME,
       JOINDATE,
       DATEDIFF(YEAR,JOINDATE,GETDATE()) 
       AS EXPYEARS
FROM EMPLOYEE;

----------------------------------------------------------------------------

--QUESTION10

CREATE TABLE EMPLOYEEDUPLICATE     --USING SAME DETAILS AS FROM FIRST QUESTION
(
EMP_ID INT,
EMP_NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY INT,
JOINDATE DATE
);

INSERT INTO EMPLOYEEDUPLICATE
VALUES
(101,'VARUN','HR',74000,'2024-11-25'),
(102,'ROY','TEACHING',50000,'2020-04-14'),
(103,'SASHA','FINANCE',95000,'2021-07-04'),
(104,'ARJUN','IT',70000,'2023-11-25'),
(105,'HEMA','TEACHING',52000,'2021-05-14'),
(106,'INDU','CODING',195000,'2019-04-04'),
(104,'ARJUN','IT',70000,'2023-11-25'),
(102,'ROY','TEACHING',50000,'2020-04-14');

SELECT * FROM EMPLOYEEDUPLICATE;

SELECT EMP_ID, 
       EMP_NAME, 
       DEPARTMENT, 
       SALARY,
       JOINDATE,
       COUNT(*) AS DUPECOUNT
FROM EMPLOYEEDUPLICATE
GROUP BY EMP_ID,
         EMP_NAME, 
         DEPARTMENT, 
         SALARY,
         JOINDATE
HAVING COUNT(*)>1;

SELECT DISTINCT EMP_ID, 
                EMP_NAME, 
                DEPARTMENT, 
                SALARY,
                JOINDATE
FROM EMPLOYEEDUPLICATE;

WITH DUPEEMP AS 
(
SELECT *,
ROW_NUMBER() OVER 
(
PARTITION BY EMP_ID, 
             EMP_NAME, 
             DEPARTMENT, 
             SALARY, 
             JOINDATE
             ORDER BY EMP_ID
) 
AS ROWNUM
FROM EMPLOYEEDUPLICATE
)
DELETE FROM DUPEEMP
WHERE ROWNUM>1;

SELECT * FROM EMPLOYEEDUPLICATE;

----------------------------------------------------------------------------

--BONUSQUESTION

SELECT EMP_NAME,
       SALARY,
       CASE
           WHEN SALARY<30000 THEN 'LOW'
           WHEN SALARY BETWEEN 30000 AND 60000 THEN 'MEDIUM'
           WHEN SALARY>60000 THEN 'HIGH'
       END AS SALARYCATEGORY
FROM EMPLOYEE;