
--SQL PRACTICE TEST DAY 1
--------------------------------------------------------------------------------

--PART A) DATABASE AND TABLE

CREATE DATABASE COMPANYDBS

CREATE TABLE EMPLOYEE
(
EMPID INT PRIMARY KEY,
EMPNAME VARCHAR(30), 
DEPARTMENT VARCHAR(30), 
SALARY DECIMAL(10,2), 
AGE INT,
CITY VARCHAR(30)
);

INSERT INTO EMPLOYEE
VALUES
(101,'RAHUL','IT',55000,24,'KOCHI'),
(102,'ANJALI','HR',45000,26,'CHENNAI'),
(103,'KIRAN','IT',62000,29,'BANGLORE'),
(104,'SNEHA','FINANCE',70000,30,'HYDERABAD'),
(105,'ARUN','HR',48000,25,'KOCHI'),
(106,'MEENA','IT',75000,32,'CHENNAI'),
(107,'JOHN','FINANCE',65000,29,'BANGLORE'),
(108,'PRIYA','IT',52000,23,'KOCHI');

--------------------------------------------------------------------------------

--PART B) SELECT

SELECT * FROM EMPLOYEE;

SELECT EMPNAME, SALARY 
FROM EMPLOYEE;

SELECT EMPNAME, DEPARTMENT, CITY 
FROM EMPLOYEE;

SELECT SALARY 
FROM EMPLOYEE;

--------------------------------------------------------------------------------

--PART C) WHERE CLAUSE

SELECT * FROM EMPLOYEE
WHERE SALARY>50000;

SELECT * FROM EMPLOYEE
WHERE DEPARTMENT='IT';

SELECT * FROM EMPLOYEE
WHERE AGE>=28;

SELECT * FROM EMPLOYEE
WHERE CITY='KOCHI';

SELECT * FROM EMPLOYEE
WHERE SALARY>50000 AND SALARY<70000

SELECT * FROM EMPLOYEE
WHERE DEPARTMENT IN ('IT','HR');

SELECT * FROM EMPLOYEE
WHERE EMPNAME LIKE 'A%';

SELECT * FROM EMPLOYEE
WHERE EMPNAME LIKE '%A'

--------------------------------------------------------------------------------

--PART D) ORDER BY

SELECT * FROM EMPLOYEE
ORDER BY SALARY ASC;

SELECT * FROM EMPLOYEE
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEE
ORDER BY DEPARTMENT;

SELECT * FROM EMPLOYEE ORDER BY  DEPARTMENT,SALARY DESC;

--------------------------------------------------------------------------------

--PART E) AGGREGATE FUNCTIONS AND GROUP BY

SELECT COUNT(*) FROM EMPLOYEE;

SELECT MAX(SALARY) FROM EMPLOYEE;

SELECT MIN(SALARY) FROM EMPLOYEE;

SELECT AVG(SALARY) FROM EMPLOYEE;

SELECT SUM(SALARY) FROM EMPLOYEE;

SELECT DEPARTMENT,
COUNT(*) AS TOTAL
FROM EMPLOYEE
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
AVG(SALARY) AS AVGSAL
FROM EMPLOYEE
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
MAX(SALARY) AS MAXSAL
FROM EMPLOYEE
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
MIN(SALARY) AS MINSAL
FROM EMPLOYEE
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
SUM(SALARY) AS SUMSAL
FROM EMPLOYEE
GROUP BY DEPARTMENT;

--------------------------------------------------------------------------------

--PART F) HAVING CLAUSE

SELECT DEPARTMENT,
COUNT(*)
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(*)>2;

SELECT DEPARTMENT,
AVG(SALARY) AVGSAL2
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>60000;

SELECT DEPARTMENT,
SUM(SALARY) SUMSAL2
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>100000;

SELECT DEPARTMENT,
MAX(SALARY) MAXSAL2
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING MAX(SALARY)>650000;

--------------------------------------------------------------------------------

--PART G) OPERATORS

SELECT *,
SALARY+5000 AS NEW_SAL 
FROM EMPLOYEE;         

SELECT *,
SALARY-2000 AS NEW_SAL2 
FROM EMPLOYEE;

SELECT *,
SALARY*12 AS NEW_SAL3 
FROM EMPLOYEE;

SELECT *,
SALARY/12 AS NEW_SAL4 
FROM EMPLOYEE;

--------------------------------------------------------------------------------

--PART H) COMPARISON OPERATORS

SELECT * FROM EMPLOYEE
WHERE SALARY=55000;   

SELECT * FROM EMPLOYEE
WHERE SALARY!=55000;

--------------------------------------------------------------------------------

--PART G) LOGICAL OPERATORS

SELECT * FROM EMPLOYEE
WHERE SALARY>50000 AND CITY='KOCHI';

SELECT * FROM EMPLOYEE
WHERE DEPARTMENT>'IT' OR DEPARTMENT='FINANCE';

--------------------------------------------------------------------------------

--PART H) SPECIAL OPERATORS

SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 45000 AND 75000;

SELECT * FROM EMPLOYEE
WHERE CITY IN ('KOCHI','CHENNAI');

SELECT * FROM EMPLOYEE
WHERE EMPNAME LIKE 'R%';

--NAME WITH A??
SELECT * FROM EMPLOYEE
WHERE EMPNAME LIKE '%A%';

--------------------------------------------------------------------------------

--PART I) BONUS QUESTIONS

UPDATE EMPLOYEE
SET SALARY=60000
WHERE EMPID=101;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE
WHERE EMPID=108;

ALTER TABLE EMPLOYEE
ADD EMAIL VARCHAR(30);

SELECT * FROM EMPLOYEE;

--------------------------------------------------------------------------------